#!/bin/bash

set -e
set -x

#JAVA_DISTRIBUTION="openjdk" 
#JAVA_VERSION="8"
echo "JAVA_DISTRIBUTION: ${JAVA_DISTRIBUTION}"
echo "JAVA_VERSION: ${JAVA_VERSION}"

apt-get update -y

apt-get install "openjdk-${JAVA_VERSION}-jdk" -y

# basic sanity check
java -version

# clean up steps
apt-get autoremove -y 
apt-get clean

rm -rf /var/lib/{apt,cache,log}/
