#!/bin/bash

set -e
set -x

#MAVEN_VERSION="3.5.2" 
echo "MAVEN_VERSION: ${MAVEN_VERSION}"

PURGE_WGET=false
if ! [ -x "$(command -v wget)" ]; then
  PURGE_WGET=true
  apt-get update -y
  apt-get install -y wget
fi

wget http://repo1.maven.org/maven2/org/apache/maven/apache-maven/${MAVEN_VERSION}/apache-maven-${MAVEN_VERSION}-bin.tar.gz
tar xzvf apache-maven-${MAVEN_VERSION}-bin.tar.gz

mkdir -p /opt
mv apache-maven-${MAVEN_VERSION} /opt
ln -s /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /bin/mvn
ln -s /opt/apache-maven-${MAVEN_VERSION}/bin/mvnDebug /bin/mvnDebug

# clean up steps
rm -rf apache-maven-${MAVEN_VERSION}-bin.tar.gz
if [[ ( "$PURGE_WGET" == 'true' ) ]] ; then
  apt-get remove --purge -y wget
fi
apt-get autoremove -y 
apt-get clean

rm -rf /var/lib/{apt,cache,log}/

# basic sanity check
mvn -version
