#!/bin/bash

set -e
set -x

#JAVA_DISTRIBUTION="oraclejdk" 
#JAVA_VERSION="8"
echo "JAVA_DISTRIBUTION: ${JAVA_DISTRIBUTION}"
echo "JAVA_VERSION: ${JAVA_VERSION}"

echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections

apt-get update -y
apt-get install -y software-properties-common
add-apt-repository -y ppa:webupd8team/java
apt-get update -y
apt-get install -y oracle-java${JAVA_VERSION}-installer

# basic sanity check
java -version

# clean up steps
apt-get remove --purge -y software-properties-common
apt-get autoremove -y 
apt-get clean

rm -rf /var/lib/{apt,cache,log}/
rm -rf /var/cache/oracle-jdk${JAVA_VERSION}-installer
