#!/bin/bash

set -e
set -x

apt-get update -y
apt-get install -y wget

#MAVEN_VERSION="3.5.2" 
echo "MAVEN_VERSION: ${MAVEN_VERSION}"

wget http://repo1.maven.org/maven2/org/apache/maven/apache-maven/${MAVEN_VERSION}/apache-maven-${MAVEN_VERSION}-bin.tar.gz
tar xzvf apache-maven-${MAVEN_VERSION}-bin.tar.gz

mkdir -p /opt
mv apache-maven-${MAVEN_VERSION} /opt
ln -s /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /bin/mvn
ln -s /opt/apache-maven-${MAVEN_VERSION}/bin/mvnDebug /bin/mvnDebug

mvn -version

# clean up steps
rm -rf apache-maven-${MAVEN_VERSION}-bin.tar.gz
apt-get remove --purge -y wget
apt-get autoremove -y 
apt-get clean

rm -rf /var/lib/{apt,cache,log}/
